"""
The template module provides means for generating various business
documents. The Business Documents are based on the Universal Business
Language (UBL) XML schema definitions.
See: http://docs.oasis-open.org/ubl/os-UBL-2.1/UBL-2.1.html

The python implementation closely follows the the xml
class definition. It does not however, follow a one-to-one conversion of xml
schema to python classes. A lose mapping which allows for flexibility and
extension of the python implementation was adopted to enable developers use
the UBL standard across various scenarios without rigid boundaries.
This means, the python implementation is designed to allow for developers to
have wrapper classes which performs as Business Document (BusinessDocument) or
can be parsed into a printable documents. Achieving this is done by defining
the various Business Information Elements (BIE) as specified in UBL 2.1

Collection of classes in this module will include:
* BusinessDocumentTemplate
Utility classes private to this module will be used to generate various
types of Business documents such as Order, Invoice etc. dynamically from
specifying the named document type.

"""
from enum import IntEnum, unique
from ubl.utils import Singleton
from collections import OrderedDict
from datetime import datetime
from hashlib import sha512
import copy

# @todo: do you export the various template or only the factory?

__all__ = (
    'ApplicationResponse',
    'AttachedDocument',
    'UnawardedNotification',
    'BillOfLading',
    'CallForTenders',
    'Catalogue',
    'CatalogueDeletion',
    'CatalogueItemSpecificationUpdate',
    'CataloguePricingUpdate',
    'CatalogueRequest',
    'CertificateOfOrigin',
    'ContractAwardNotice',
    'ContractNotice',
    'CreditNote',
    'DebitNote',
    'DespatchAdvice',
    'DocumentStatus',
    'DocumentStatusRequest',
    'ExceptionCriteria',
    'ExceptionNotification',
    'Forecast',
    'ForecastRevision',
    'ForwardingInstructions',
    'FreightInvoice',
    'FulfilmentCancellation',
    'GoodsItemItinerary',
    'GuaranteeCertificate',
    'InstructionForReturns',
    'InventoryReport',
    'Invoice',
    'ItemInformationRequest',
    'Order',
    'OrderCancellation',
    'OrderChange',
    'OrderResponse',
    'OrderResponseSimple',
    'PackingList',
    'PriorInformationNotice',
    'ProductActivity',
    'Quotation',
    'ReceiptAdvice',
    'Reminder',
    'RemittanceAdvice',
    'RequestForQuotation',
    'RetailEvent',
    'SelfBilledCreditNote',
    'SelfBilledInvoice',
    'Statement',
    'StockAvailabilityReport',
    'Tender',
    'TendererQualification',
    'TendererQualificationResponse',
    'TenderReceipt',
    'TradeItemLocationProfile',
    'TransportationStatus',
    'TransportationStatusRequest',
    'TransportExecutionPlan',
    'TransportExecutionPlanRequest',
    'TransportProgressStatus',
    'TransportProgressStatusRequest',
    'TransportServiceDescription',
    'TransportServiceDescriptionRequest',
    'UtilityStatement',
    'Waybill',
    'BusinessDocumentPrototype',
    'DocumentRevisions'
)


@unique
class _BusinessInformationElementFlag(IntEnum):
    """
    List of the Business Information Elements as defined in UBL 2.1
    """
    ACCEPTED_INDICATOR = 1
    ACCEPTED_VARIANTS_DESCRIPTION = 2
    ACCOUNT_FORMAT_CODE = 3
    ACCOUNT_ID = 4
    ACCOUNT_TYPE_CODE = 5
    ACCOUNTING_COST = 6
    ACCOUNTING_COST_CODE = 7
    ACTION_CODE = 8
    ACTIVITY_TYPE = 9
    ACTIVITY_TYPE_CODE = 10
    ACTUAL_DELIVERY_DATE = 11
    ACTUAL_DELIVERY_TIME = 12
    ACTUAL_DESPATCH_DATE = 13
    ACTUAL_DESPATCH_TIME = 14
    ACTUAL_PICKUP_DATE = 15
    ACTUAL_PICKUP_TIME = 16
    ACTUAL_TEMPERATURE_REDUCTION_QUANTITY = 17
    AD_VALOREM_INDICATOR = 18
    ADDITIONAL_ACCOUNT_ID = 19
    ADDITIONAL_CONDITIONS = 20
    ADDITIONAL_INFORMATION = 21
    ADDITIONAL_STREET_NAME = 22
    ADDRESS_FORMAT_CODE = 23
    ADDRESS_TYPE_CODE = 24
    ADJUSTMENT_REASON_CODE = 25
    ADMISSION_CODE = 26
    ADVERTISEMENT_AMOUNT = 27
    AGENCY_ID = 28
    AGENCY_NAME = 29
    AIR_FLOW_PERCENT = 30
    AIRCRAFT_ID = 31
    ALIAS_NAME = 32
    ALLOWANCE_CHARGE_REASON = 33
    ALLOWANCE_CHARGE_REASON_CODE = 34
    ALLOWANCE_TOTAL_AMOUNT = 35
    ALTITUDE_MEASURE = 36
    AMOUNT = 37
    AMOUNT_RATE = 38
    ANIMAL_FOOD_APPROVED_INDICATOR = 39
    ANIMAL_FOOD_INDICATOR = 40
    ANNUAL_AVERAGE_AMOUNT = 41
    APPLICATION_STATUS_CODE = 42
    APPROVAL_DATE = 43
    APPROVAL_STATUS = 44
    ATTRIBUTE_ID = 45
    AUCTION_CONSTRAINT_INDICATOR = 46
    AUCTION_URI = 47
    AVAILABILITY_DATE = 48
    AVAILABILITY_STATUS_CODE = 49
    AVERAGE_AMOUNT = 50
    AVERAGE_SUBSEQUENT_CONTRACT_AMOUNT = 51
    AWARD_DATE = 52
    AWARD_TIME = 53
    AWARDING_CRITERION_DESCRIPTION = 54
    AWARDING_CRITERION_ID = 55
    AWARDING_CRITERION_TYPE_CODE = 56
    AWARDING_METHOD_TYPE_CODE = 57
    BACK_ORDER_ALLOWED_INDICATOR = 58
    BACKORDER_QUANTITY = 59
    BACKORDER_REASON = 60
    BALANCE_AMOUNT = 61
    BALANCE_BROUGHT_FORWARD_INDICATOR = 62
    BARCODE_SYMBOLOGY_ID = 63
    BASE_AMOUNT = 64
    BASE_QUANTITY = 65
    BASE_UNIT_MEASURE = 66
    BASED_ON_CONSENSUS_INDICATOR = 67
    BASIC_CONSUMED_QUANTITY = 68
    BATCH_QUANTITY = 69
    BEST_BEFORE_DATE = 70
    BINDING_ON_BUYER_INDICATOR = 71
    BIRTH_DATE = 72
    BIRTHPLACE_NAME = 73
    BLOCK_NAME = 74
    BRAND_NAME = 75
    BROKER_ASSIGNED_ID = 76
    BUDGET_YEAR_NUMERIC = 77
    BUILDING_NAME = 78
    BUILDING_NUMBER = 79
    BULK_CARGO_INDICATOR = 80
    BUSINESS_CLASSIFICATION_EVIDENCE_ID = 81
    BUSINESS_IDENTITY_EVIDENCE_ID = 82
    BUYER_EVENT_ID = 83
    BUYER_PROFILE_URI = 84
    BUYER_REFERENCE = 85
    CV2ID = 86
    CALCULATION_EXPRESSION = 87
    CALCULATION_EXPRESSION_CODE = 88
    CALCULATION_METHOD_CODE = 89
    CALCULATION_RATE = 90
    CALCULATION_SEQUENCE_NUMERIC = 91
    CALL_BASE_AMOUNT = 92
    CALL_DATE = 93
    CALL_EXTENSION_AMOUNT = 94
    CALL_TIME = 95
    CANCELLATION_NOTE = 96
    CANDIDATE_REDUCTION_CONSTRAINT_INDICATOR = 97
    CANDIDATE_STATEMENT = 98
    CANONICALIZATION_METHOD = 99
    CAPABILITY_TYPE_CODE = 100
    CARD_CHIP_CODE = 101
    CARD_TYPE_CODE = 102
    CARGO_TYPE_CODE = 103
    CARRIER_ASSIGNED_ID = 104
    CARRIER_SERVICE_INSTRUCTIONS = 105
    CATALOGUE_INDICATOR = 106
    CATEGORY_NAME = 107
    CERTIFICATE_TYPE = 108
    CERTIFICATE_TYPE_CODE = 109
    CHANGE_CONDITIONS = 110
    CHANNEL = 111
    CHANNEL_CODE = 112
    CHARACTER_SET_CODE = 113
    CHARACTERISTICS = 114
    CHARGE_INDICATOR = 115
    CHARGE_TOTAL_AMOUNT = 116
    CHARGEABLE_QUANTITY = 117
    CHARGEABLE_WEIGHT_MEASURE = 118
    CHILD_CONSIGNMENT_QUANTITY = 119
    CHIP_APPLICATION_ID = 120
    CITY_NAME = 121
    CITY_SUBDIVISION_NAME = 122
    CODE_VALUE = 123
    COLLABORATION_PRIORITY_CODE = 124
    COMMENT = 125
    COMMODITY_CODE = 126
    COMPANY_ID = 127
    COMPANY_LEGAL_FORM = 128
    COMPANY_LEGAL_FORM_CODE = 129
    COMPANY_LIQUIDATION_STATUS_CODE = 130
    COMPARED_VALUE_MEASURE = 131
    COMPARISON_DATA_CODE = 132
    COMPARISON_DATA_SOURCE_CODE = 133
    COMPARISON_FORECAST_ISSUE_DATE = 134
    COMPARISON_FORECAST_ISSUE_TIME = 135
    COMPLETION_INDICATOR = 136
    CONDITION = 137
    CONDITION_CODE = 138
    CONDITIONS = 139
    CONDITIONS_DESCRIPTION = 140
    CONSIGNEE_ASSIGNED_ID = 141
    CONSIGNMENT_QUANTITY = 142
    CONSIGNOR_ASSIGNED_ID = 143
    CONSOLIDATABLE_INDICATOR = 144
    CONSTITUTION_CODE = 145
    CONSUMER_INCENTIVE_TACTIC_TYPE_CODE = 146
    CONSUMER_UNIT_QUANTITY = 147
    CONSUMERS_ENERGY_LEVEL = 148
    CONSUMERS_ENERGY_LEVEL_CODE = 149
    CONSUMPTION_ENERGY_QUANTITY = 150
    CONSUMPTION_ID = 151
    CONSUMPTION_LEVEL = 152
    CONSUMPTION_LEVEL_CODE = 153
    CONSUMPTION_REPORT_ID = 154
    CONSUMPTION_TYPE = 155
    CONSUMPTION_TYPE_CODE = 156
    CONSUMPTION_WATER_QUANTITY = 157
    CONTAINERIZED_INDICATOR = 158
    CONTENT = 159
    CONTENT_UNIT_QUANTITY = 160
    CONTRACT_FOLDER_ID = 161
    CONTRACT_NAME = 162
    CONTRACT_SUBDIVISION = 163
    CONTRACT_TYPE = 164
    CONTRACT_TYPE_CODE = 165
    CONTRACTED_CARRIER_ASSIGNED_ID = 166
    CONTRACTING_SYSTEM_CODE = 167
    COORDINATE_SYSTEM_CODE = 168
    COPY_INDICATOR = 169
    CORPORATE_REGISTRATION_TYPE_CODE = 170
    CORPORATE_STOCK_AMOUNT = 171
    CORRECTION_AMOUNT = 172
    CORRECTION_TYPE = 173
    CORRECTION_TYPE_CODE = 174
    CORRECTION_UNIT_AMOUNT = 175
    COUNTRY_SUBENTITY = 176
    COUNTRY_SUBENTITY_CODE = 177
    CREDIT_LINE_AMOUNT = 178
    CREDIT_NOTE_TYPE_CODE = 179
    CREDITED_QUANTITY = 180
    CREW_QUANTITY = 181
    CURRENCY_CODE = 182
    CURRENT_CHARGE_TYPE = 183
    CURRENT_CHARGE_TYPE_CODE = 184
    CUSTOMER_ASSIGNED_ACCOUNT_ID = 185
    CUSTOMER_REFERENCE = 186
    CUSTOMIZATION_ID = 187
    CUSTOMS_CLEARANCE_SERVICE_INSTRUCTIONS = 188
    CUSTOMS_IMPORT_CLASSIFIED_INDICATOR = 189
    CUSTOMS_STATUS_CODE = 190
    CUSTOMS_TARIFF_QUANTITY = 191
    DAMAGE_REMARKS = 192
    DANGEROUS_GOODS_APPROVED_INDICATOR = 193
    DATA_SENDING_CAPABILITY = 194
    DATA_SOURCE_CODE = 195
    DATE = 196
    DEBIT_LINE_AMOUNT = 197
    DEBITED_QUANTITY = 198
    DECLARATION_TYPE_CODE = 199
    DECLARED_CARRIAGE_VALUE_AMOUNT = 200
    DECLARED_CUSTOMS_VALUE_AMOUNT = 201
    DECLARED_FOR_CARRIAGE_VALUE_AMOUNT = 202
    DECLARED_STATISTICS_VALUE_AMOUNT = 203
    DELIVERED_QUANTITY = 204
    DELIVERY_INSTRUCTIONS = 205
    DEMURRAGE_INSTRUCTIONS = 206
    DEPARTMENT = 207
    DESCRIPTION = 208
    DESCRIPTION_CODE = 209
    DESPATCH_ADVICE_TYPE_CODE = 210
    DIFFERENCE_TEMPERATURE_REDUCTION_QUANTITY = 211
    DIRECTION_CODE = 212
    DISPLAY_TACTIC_TYPE_CODE = 213
    DISPOSITION_CODE = 214
    DISTRICT = 215
    DOCUMENT_CURRENCY_CODE = 216
    DOCUMENT_DESCRIPTION = 217
    DOCUMENT_HASH = 218
    DOCUMENT_ID = 219
    DOCUMENT_STATUS_CODE = 220
    DOCUMENT_STATUS_REASON_CODE = 221
    DOCUMENT_STATUS_REASON_DESCRIPTION = 222
    DOCUMENT_TYPE = 223
    DOCUMENT_TYPE_CODE = 224
    DOCUMENTATION_FEE_AMOUNT = 225
    DUE_DATE = 226
    DURATION_MEASURE = 227
    DUTY = 228
    DUTY_CODE = 229
    EARLIEST_PICKUP_DATE = 230
    EARLIEST_PICKUP_TIME = 231
    ECONOMIC_OPERATOR_REGISTRY_URI = 232
    EFFECTIVE_DATE = 233
    EFFECTIVE_TIME = 234
    ELECTRONIC_DEVICE_DESCRIPTION = 235
    ELECTRONIC_MAIL = 236
    EMBEDDED_DOCUMENT_BINARY_OBJECT = 237
    EMERGENCY_PROCEDURES_CODE = 238
    EMPLOYEE_QUANTITY = 239
    ENCODING_CODE = 240
    END_DATE = 241
    END_TIME = 242
    ENDPOINT_ID = 243
    ENVIRONMENTAL_EMISSION_TYPE_CODE = 244
    ESTIMATED_AMOUNT = 245
    ESTIMATED_CONSUMED_QUANTITY = 246
    ESTIMATED_DELIVERY_DATE = 247
    ESTIMATED_DELIVERY_TIME = 248
    ESTIMATED_DESPATCH_DATE = 249
    ESTIMATED_DESPATCH_TIME = 250
    ESTIMATED_OVERALL_CONTRACT_AMOUNT = 251
    ESTIMATED_OVERALL_CONTRACT_QUANTITY = 252
    EVALUATION_CRITERION_TYPE_CODE = 253
    EVIDENCE_TYPE_CODE = 254
    EXCEPTION_RESOLUTION_CODE = 255
    EXCEPTION_STATUS_CODE = 256
    EXCHANGE_MARKET_ID = 257
    EXCLUSION_REASON = 258
    EXECUTION_REQUIREMENT_CODE = 259
    EXEMPTION_REASON = 260
    EXEMPTION_REASON_CODE = 261
    EXPECTED_OPERATOR_QUANTITY = 262
    EXPECTED_QUANTITY = 263
    EXPENSE_CODE = 264
    EXPIRY_DATE = 265
    EXPIRY_TIME = 266
    EXPRESSION = 267
    EXPRESSION_CODE = 268
    EXTENDED_ID = 269
    EXTENSION = 270
    FACE_VALUE_AMOUNT = 271
    FAMILY_NAME = 272
    FEATURE_TACTIC_TYPE_CODE = 273
    FEE_AMOUNT = 274
    FEE_DESCRIPTION = 275
    FILE_NAME = 276
    FINANCING_INSTRUMENT_CODE = 277
    FIRST_NAME = 278
    FIRST_SHIPMENT_AVAILIBILITY_DATE = 279
    FLOOR = 280
    FOLLOWUP_CONTRACT_INDICATOR = 281
    FORECAST_PURPOSE_CODE = 282
    FORECAST_TYPE_CODE = 283
    FORMAT_CODE = 284
    FORWARDER_SERVICE_INSTRUCTIONS = 285
    FREE_OF_CHARGE_INDICATOR = 286
    FREE_ON_BOARD_VALUE_AMOUNT = 287
    FREIGHT_FORWARDER_ASSIGNED_ID = 288
    FREIGHT_RATE_CLASS_CODE = 289
    FREQUENCY = 290
    FROZEN_DOCUMENT_INDICATOR = 291
    FROZEN_PERIOD_DAYS_NUMERIC = 292
    FULLNESS_INDICATION_CODE = 293
    FULLY_PAID_SHARES_INDICATOR = 294
    FUNDING_PROGRAM = 295
    FUNDING_PROGRAM_CODE = 296
    GAS_PRESSURE_QUANTITY = 297
    GENDER_CODE = 298
    GENERAL_CARGO_INDICATOR = 299
    GOVERNMENT_AGREEMENT_CONSTRAINT_INDICATOR = 300
    GROSS_TONNAGE_MEASURE = 301
    GROSS_VOLUME_MEASURE = 302
    GROSS_WEIGHT_MEASURE = 303
    GUARANTEE_TYPE_CODE = 304
    GUARANTEED_DESPATCH_DATE = 305
    GUARANTEED_DESPATCH_TIME = 306
    HANDLING_CODE = 307
    HANDLING_INSTRUCTIONS = 308
    HASH_ALGORITHM_METHOD = 309
    HAULAGE_INSTRUCTIONS = 310
    HAZARD_CLASS_ID = 311
    HAZARDOUS_CATEGORY_CODE = 312
    HAZARDOUS_REGULATION_CODE = 313
    HAZARDOUS_RISK_INDICATOR = 314
    HEATING_TYPE = 315
    HEATING_TYPE_CODE = 316
    HIGHER_TENDER_AMOUNT = 317
    HOLDER_NAME = 318
    HUMAN_FOOD_APPROVED_INDICATOR = 319
    HUMAN_FOOD_INDICATOR = 320
    HUMIDITY_PERCENT = 321
    ID = 322
    IDENTIFICATION_CODE = 323
    IDENTIFICATION_ID = 324
    IMMOBILIZATION_CERTIFICATE_ID = 325
    IMPORTANCE_CODE = 326
    INDICATION_INDICATOR = 327
    INDUSTRY_CLASSIFICATION_CODE = 328
    INFORMATION = 329
    INFORMATION_URI = 330
    INHALATION_TOXICITY_ZONE_CODE = 331
    INHOUSE_MAIL = 332
    INSPECTION_METHOD_CODE = 333
    INSTALLMENT_DUE_DATE = 334
    INSTRUCTION_ID = 335
    INSTRUCTION_NOTE = 336
    INSTRUCTIONS = 337
    INSURANCE_PREMIUM_AMOUNT = 338
    INSURANCE_VALUE_AMOUNT = 339
    INVENTORY_VALUE_AMOUNT = 340
    INVOICE_TYPE_CODE = 341
    INVOICED_QUANTITY = 342
    INVOICING_PARTY_REFERENCE = 343
    ISSUE_DATE = 344
    ISSUE_NUMBER_ID = 345
    ISSUE_TIME = 346
    ISSUER_ID = 347
    ITEM_CLASSIFICATION_CODE = 348
    ITEM_UPDATE_REQUEST_INDICATOR = 349
    JOB_TITLE = 350
    JOURNEY_ID = 351
    JUSTIFICATION = 352
    JUSTIFICATION_DESCRIPTION = 353
    KEYWORD = 354
    LANGUAGE_ID = 355
    LAST_REVISION_DATE = 356
    LAST_REVISION_TIME = 357
    LATEST_DELIVERY_DATE = 358
    LATEST_DELIVERY_TIME = 359
    LATEST_METER_QUANTITY = 360
    LATEST_METER_READING_DATE = 361
    LATEST_METER_READING_METHOD = 362
    LATEST_METER_READING_METHOD_CODE = 363
    LATEST_PICKUP_DATE = 364
    LATEST_PICKUP_TIME = 365
    LATEST_PROPOSAL_ACCEPTANCE_DATE = 366
    LATEST_SECURITY_CLEARANCE_DATE = 367
    LATITUDE_DEGREES_MEASURE = 368
    LATITUDE_DIRECTION_CODE = 369
    LATITUDE_MINUTES_MEASURE = 370
    LEAD_TIME_MEASURE = 371
    LEGAL_REFERENCE = 372
    LEGAL_STATUS_INDICATOR = 373
    LIABILITY_AMOUNT = 374
    LICENSE_PLATE_ID = 375
    LIFE_CYCLE_STATUS_CODE = 376
    LIMITATION_DESCRIPTION = 377
    LINE = 378
    LINE_COUNT_NUMERIC = 379
    LINE_EXTENSION_AMOUNT = 380
    LINE_ID = 381
    LINE_NUMBER_NUMERIC = 382
    LINE_STATUS_CODE = 383
    LIST_VALUE = 384
    LIVESTOCK_INDICATOR = 385
    LOADING_LENGTH_MEASURE = 386
    LOADING_SEQUENCE_ID = 387
    LOCALE_CODE = 388
    LOCATION = 389
    LOCATION_ID = 390
    LOCATION_TYPE_CODE = 391
    LOGIN = 392
    LOGO_REFERENCE_ID = 393
    LONGITUDE_DEGREES_MEASURE = 394
    LONGITUDE_DIRECTION_CODE = 395
    LONGITUDE_MINUTES_MEASURE = 396
    LOSS_RISK = 397
    LOSS_RISK_RESPONSIBILITY_CODE = 398
    LOT_NUMBER_ID = 399
    LOW_TENDERS_DESCRIPTION = 400
    LOWER_ORANGE_HAZARD_PLACARD_ID = 401
    LOWER_TENDER_AMOUNT = 402
    MANDATE_TYPE_CODE = 403
    MANUFACTURE_DATE = 404
    MANUFACTURE_TIME = 405
    MARK_ATTENTION = 406
    MARK_ATTENTION_INDICATOR = 407
    MARK_CARE = 408
    MARK_CARE_INDICATOR = 409
    MARKET_VALUE_AMOUNT = 410
    MARKING_ID = 411
    MATHEMATIC_OPERATOR_CODE = 412
    MAXIMUM_ADVERTISEMENT_AMOUNT = 413
    MAXIMUM_AMOUNT = 414
    MAXIMUM_BACKORDER_QUANTITY = 415
    MAXIMUM_COPIES_NUMERIC = 416
    MAXIMUM_MEASURE = 417
    MAXIMUM_NUMBER_NUMERIC = 418
    MAXIMUM_OPERATOR_QUANTITY = 419
    MAXIMUM_ORDER_QUANTITY = 420
    MAXIMUM_PAID_AMOUNT = 421
    MAXIMUM_PAYMENT_INSTRUCTIONS_NUMERIC = 422
    MAXIMUM_PERCENT = 423
    MAXIMUM_QUANTITY = 424
    MAXIMUM_VALUE = 425
    MAXIMUM_VARIANT_QUANTITY = 426
    MEASURE = 427
    MEDICAL_FIRST_AID_GUIDE_CODE = 428
    METER_CONSTANT = 429
    METER_CONSTANT_CODE = 430
    METER_NAME = 431
    METER_NUMBER = 432
    METER_READING_COMMENTS = 433
    METER_READING_TYPE = 434
    METER_READING_TYPE_CODE = 435
    MIDDLE_NAME = 436
    MIME_CODE = 437
    MINIMUM_AMOUNT = 438
    MINIMUM_BACKORDER_QUANTITY = 439
    MINIMUM_IMPROVEMENT_BID = 440
    MINIMUM_INVENTORY_QUANTITY = 441
    MINIMUM_MEASURE = 442
    MINIMUM_NUMBER_NUMERIC = 443
    MINIMUM_ORDER_QUANTITY = 444
    MINIMUM_PERCENT = 445
    MINIMUM_QUANTITY = 446
    MINIMUM_VALUE = 447
    MISCELLANEOUS_EVENT_TYPE_CODE = 448
    MODEL_NAME = 449
    MONETARY_SCOPE = 450
    MOVIE_TITLE = 451
    MULTIPLE_ORDER_QUANTITY = 452
    MULTIPLIER_FACTOR_NUMERIC = 453
    NAME = 454
    NAME_CODE = 455
    NAME_SUFFIX = 456
    NATIONALITY_ID = 457
    NATURE_CODE = 458
    NEGOTIATION_DESCRIPTION = 459
    NET_NET_WEIGHT_MEASURE = 460
    NET_TONNAGE_MEASURE = 461
    NET_VOLUME_MEASURE = 462
    NET_WEIGHT_MEASURE = 463
    NETWORK_ID = 464
    NOMINATION_DATE = 465
    NOMINATION_TIME = 466
    NORMAL_TEMPERATURE_REDUCTION_QUANTITY = 467
    NOTE = 468
    NOTIFICATION_TYPE_CODE = 469
    OCCURRENCE_DATE = 470
    OCCURRENCE_TIME = 471
    ON_CARRIAGE_INDICATOR = 472
    ONE_TIME_CHARGE_TYPE = 473
    ONE_TIME_CHARGE_TYPE_CODE = 474
    ONTOLOGY_URI = 475
    OPEN_TENDER_ID = 476
    OPERATING_YEARS_QUANTITY = 477
    OPTIONAL_LINE_ITEM_INDICATOR = 478
    OPTIONS_DESCRIPTION = 479
    ORDER_INTERVAL_DAYS_NUMERIC = 480
    ORDER_QUANTITY_INCREMENT_NUMERIC = 481
    ORDER_RESPONSE_CODE = 482
    ORDER_TYPE_CODE = 483
    ORDERABLE_INDICATOR = 484
    ORDERABLE_UNIT = 485
    ORDERABLE_UNIT_FACTOR_RATE = 486
    ORGANIZATION_DEPARTMENT = 487
    ORIGINAL_CONTRACTING_SYSTEM_ID = 488
    ORIGINAL_JOB_ID = 489
    OTHER_CONDITIONS_INDICATOR = 490
    OTHER_INSTRUCTION = 491
    OTHER_NAME = 492
    OUTSTANDING_QUANTITY = 493
    OUTSTANDING_REASON = 494
    OVERSUPPLY_QUANTITY = 495
    OWNER_TYPE_CODE = 496
    PACK_LEVEL_CODE = 497
    PACK_QUANTITY = 498
    PACK_SIZE_NUMERIC = 499
    PACKAGE_LEVEL_CODE = 500
    PACKAGING_TYPE_CODE = 501
    PACKING_CRITERIA_CODE = 502
    PACKING_MATERIAL = 503
    PAID_AMOUNT = 504
    PAID_DATE = 505
    PAID_TIME = 506
    PARENT_DOCUMENT_ID = 507
    PARENT_DOCUMENT_LINE_REFERENCE_ID = 508
    PARENT_DOCUMENT_TYPE_CODE = 509
    PARENT_DOCUMENT_VERSION_ID = 510
    PART_PRESENTATION_CODE = 511
    PARTECIPATION_PERCENT = 512
    PARTIAL_DELIVERY_INDICATOR = 513
    PARTICIPATION_PERCENT = 514
    PARTY_CAPACITY_AMOUNT = 515
    PARTY_TYPE = 516
    PARTY_TYPE_CODE = 517
    PASSENGER_QUANTITY = 518
    PASSWORD = 519
    PAY_PER_VIEW = 520
    PAYABLE_ALTERNATIVE_AMOUNT = 521
    PAYABLE_AMOUNT = 522
    PAYABLE_ROUNDING_AMOUNT = 523
    PAYER_REFERENCE = 524
    PAYMENT_ALTERNATIVE_CURRENCY_CODE = 525
    PAYMENT_CHANNEL_CODE = 526
    PAYMENT_CURRENCY_CODE = 527
    PAYMENT_DESCRIPTION = 528
    PAYMENT_DUE_DATE = 529
    PAYMENT_FREQUENCY_CODE = 530
    PAYMENT_ID = 531
    PAYMENT_MEANS_CODE = 532
    PAYMENT_MEANS_ID = 533
    PAYMENT_NOTE = 534
    PAYMENT_ORDER_REFERENCE = 535
    PAYMENT_PERCENT = 536
    PAYMENT_PURPOSE_CODE = 537
    PAYMENT_TERMS_DETAILS_URI = 538
    PENALTY_AMOUNT = 539
    PENALTY_SURCHARGE_PERCENT = 540
    PER_UNIT_AMOUNT = 541
    PERCENT = 542
    PERFORMANCE_METRIC_TYPE_CODE = 543
    PERFORMANCE_VALUE_QUANTITY = 544
    PERFORMING_CARRIER_ASSIGNED_ID = 545
    PERSONAL_SITUATION = 546
    PHONE_NUMBER = 547
    PLACARD_ENDORSEMENT = 548
    PLACARD_NOTATION = 549
    PLANNED_DATE = 550
    PLOT_IDENTIFICATION = 551
    POSITION_CODE = 552
    POST_EVENT_NOTIFICATION_DURATION_MEASURE = 553
    POSTAL_ZONE = 554
    POSTBOX = 555
    POWER_INDICATOR = 556
    PRE_CARRIAGE_INDICATOR = 557
    PRE_EVENT_NOTIFICATION_DURATION_MEASURE = 558
    PREFERENCE_CRITERION_CODE = 559
    PREPAID_AMOUNT = 560
    PREPAID_INDICATOR = 561
    PREPAID_PAYMENT_REFERENCE_ID = 562
    PREVIOUS_CANCELLATION_REASON_CODE = 563
    PREVIOUS_JOB_ID = 564
    PREVIOUS_METER_QUANTITY = 565
    PREVIOUS_METER_READING_DATE = 566
    PREVIOUS_METER_READING_METHOD = 567
    PREVIOUS_METER_READING_METHOD_CODE = 568
    PREVIOUS_VERSION_ID = 569
    PRICE_AMOUNT = 570
    PRICE_CHANGE_REASON = 571
    PRICE_EVALUATION_CODE = 572
    PRICE_REVISION_FORMULA_DESCRIPTION = 573
    PRICE_TYPE = 574
    PRICE_TYPE_CODE = 575
    PRICING_CURRENCY_CODE = 576
    PRICING_UPDATE_REQUEST_INDICATOR = 577
    PRIMARY_ACCOUNT_NUMBER_ID = 578
    PRINT_QUALIFIER = 579
    PRIORITY = 580
    PRIVACY_CODE = 581
    PRIZE_DESCRIPTION = 582
    PRIZE_INDICATOR = 583
    PROCEDURE_CODE = 584
    PROCESS_DESCRIPTION = 585
    PROCESS_REASON = 586
    PROCESS_REASON_CODE = 587
    PROCUREMENT_SUB_TYPE_CODE = 588
    PROCUREMENT_TYPE_CODE = 589
    PRODUCT_TRACE_ID = 590
    PROFILE_EXECUTION_ID = 591
    PROFILE_ID = 592
    PROFILE_STATUS_CODE = 593
    PROGRESS_PERCENT = 594
    PROMOTIONAL_EVENT_TYPE_CODE = 595
    PROVIDER_TYPE_CODE = 596
    PUBLISH_AWARD_INDICATOR = 597
    PURPOSE = 598
    PURPOSE_CODE = 599
    QUALITY_CONTROL_CODE = 600
    QUANTITY = 601
    QUANTITY_DISCREPANCY_CODE = 602
    RADIO_CALL_SIGN_ID = 603
    RAIL_CAR_ID = 604
    RANK = 605
    RATE = 606
    RECEIPT_ADVICE_TYPE_CODE = 607
    RECEIVED_DATE = 608
    RECEIVED_ELECTRONIC_TENDER_QUANTITY = 609
    RECEIVED_FOREIGN_TENDER_QUANTITY = 610
    RECEIVED_QUANTITY = 611
    RECEIVED_TENDER_QUANTITY = 612
    REFERENCE = 613
    REFERENCE_DATE = 614
    REFERENCE_EVENT_CODE = 615
    REFERENCE_ID = 616
    REFERENCE_TIME = 617
    REFERENCED_CONSIGNMENT_ID = 618
    REFRIGERATED_INDICATOR = 619
    REFRIGERATION_ON_INDICATOR = 620
    REGION = 621
    REGISTERED_DATE = 622
    REGISTERED_TIME = 623
    REGISTRATION_DATE = 624
    REGISTRATION_EXPIRATION_DATE = 625
    REGISTRATION_ID = 626
    REGISTRATION_NAME = 627
    REGISTRATION_NATIONALITY = 628
    REGISTRATION_NATIONALITY_ID = 629
    REGULATORY_DOMAIN = 630
    REJECT_ACTION_CODE = 631
    REJECT_REASON = 632
    REJECT_REASON_CODE = 633
    REJECTED_QUANTITY = 634
    REJECTION_NOTE = 635
    RELEASE_ID = 636
    RELIABILITY_PERCENT = 637
    REMARKS = 638
    REMINDER_SEQUENCE_NUMERIC = 639
    REMINDER_TYPE_CODE = 640
    REPLENISHMENT_OWNER_DESCRIPTION = 641
    REQUEST_FOR_QUOTATION_LINE_ID = 642
    REQUESTED_DELIVERY_DATE = 643
    REQUESTED_DESPATCH_DATE = 644
    REQUESTED_DESPATCH_TIME = 645
    REQUESTED_INVOICE_CURRENCY_CODE = 646
    REQUESTED_PUBLICATION_DATE = 647
    REQUIRED_CURRICULA_INDICATOR = 648
    REQUIRED_CUSTOMS_ID = 649
    REQUIRED_DELIVERY_DATE = 650
    REQUIRED_DELIVERY_TIME = 651
    REQUIRED_FEE_AMOUNT = 652
    RESIDENCE_TYPE = 653
    RESIDENCE_TYPE_CODE = 654
    RESIDENT_OCCUPANTS_NUMERIC = 655
    RESOLUTION = 656
    RESOLUTION_CODE = 657
    RESOLUTION_DATE = 658
    RESOLUTION_TIME = 659
    RESPONSE_CODE = 660
    RESPONSE_DATE = 661
    RESPONSE_TIME = 662
    RETAIL_EVENT_NAME = 663
    RETAIL_EVENT_STATUS_CODE = 664
    RETURNABILITY_INDICATOR = 665
    RETURNABLE_MATERIAL_INDICATOR = 666
    RETURNABLE_QUANTITY = 667
    REVISED_FORECAST_LINE_ID = 668
    REVISION_DATE = 669
    REVISION_STATUS_CODE = 670
    REVISION_TIME = 671
    ROAMING_PARTNER_NAME = 672
    ROLE_CODE = 673
    ROLE_DESCRIPTION = 674
    ROOM = 675
    ROUNDING_AMOUNT = 676
    SALES_ORDER_ID = 677
    SALES_ORDER_LINE_ID = 678
    SCHEME_URI = 679
    SEAL_ISSUER_TYPE_CODE = 680
    SEAL_STATUS_CODE = 681
    SEALING_PARTY_TYPE = 682
    SECURITY_CLASSIFICATION_CODE = 683
    SECURITY_ID = 684
    SELLER_EVENT_ID = 685
    SEQUENCE_ID = 686
    SEQUENCE_NUMBER_ID = 687
    SEQUENCE_NUMERIC = 688
    SERIAL_ID = 689
    SERVICE_INFORMATION_PREFERENCE_CODE = 690
    SERVICE_NAME = 691
    SERVICE_NUMBER_CALLED = 692
    SERVICE_TYPE = 693
    SERVICE_TYPE_CODE = 694
    SETTLEMENT_DISCOUNT_AMOUNT = 695
    SETTLEMENT_DISCOUNT_PERCENT = 696
    SHARES_NUMBER_QUANTITY = 697
    SHIPPING_MARKS = 698
    SHIPPING_ORDER_ID = 699
    SHIPPING_PRIORITY_LEVEL_CODE = 700
    SHIPS_REQUIREMENTS = 701
    SHORT_QUANTITY = 702
    SHORTAGE_ACTION_CODE = 703
    SIGNATURE_ID = 704
    SIGNATURE_METHOD = 705
    SIZE_TYPE_CODE = 706
    SOLE_PROPRIETORSHIP_INDICATOR = 707
    SOURCE_CURRENCY_BASE_RATE = 708
    SOURCE_CURRENCY_CODE = 709
    SOURCE_FORECAST_ISSUE_DATE = 710
    SOURCE_FORECAST_ISSUE_TIME = 711
    SOURCE_VALUE_MEASURE = 712
    SPECIAL_INSTRUCTIONS = 713
    SPECIAL_SECURITY_INDICATOR = 714
    SPECIAL_SERVICE_INSTRUCTIONS = 715
    SPECIAL_TERMS = 716
    SPECIAL_TRANSPORT_REQUIREMENTS = 717
    SPECIFICATION_ID = 718
    SPECIFICATION_TYPE_CODE = 719
    SPLIT_CONSIGNMENT_INDICATOR = 720
    START_DATE = 721
    START_TIME = 722
    STATEMENT_TYPE_CODE = 723
    STATUS_AVAILABLE_INDICATOR = 724
    STATUS_CODE = 725
    STATUS_REASON = 726
    STATUS_REASON_CODE = 727
    STREET_NAME = 728
    SUBCONTRACTING_CONDITIONS_CODE = 729
    SUBMISSION_DATE = 730
    SUBMISSION_DUE_DATE = 731
    SUBMISSION_METHOD_CODE = 732
    SUBSCRIBER_ID = 733
    SUBSCRIBER_TYPE = 734
    SUBSCRIBER_TYPE_CODE = 735
    SUBSTITUTION_STATUS_CODE = 736
    SUCCESSIVE_SEQUENCE_ID = 737
    SUMMARY_DESCRIPTION = 738
    SUPPLIER_ASSIGNED_ACCOUNT_ID = 739
    SUPPLY_CHAIN_ACTIVITY_TYPE_CODE = 740
    TARE_WEIGHT_MEASURE = 741
    TARGET_CURRENCY_BASE_RATE = 742
    TARGET_CURRENCY_CODE = 743
    TARGET_INVENTORY_QUANTITY = 744
    TARGET_SERVICE_PERCENT = 745
    TARIFF_CLASS_CODE = 746
    TARIFF_CODE = 747
    TARIFF_DESCRIPTION = 748
    TAX_AMOUNT = 749
    TAX_CURRENCY_CODE = 750
    TAX_ENERGY_AMOUNT = 751
    TAX_ENERGY_BALANCE_AMOUNT = 752
    TAX_ENERGY_ON_ACCOUNT_AMOUNT = 753
    TAX_EVIDENCE_INDICATOR = 754
    TAX_EXCLUSIVE_AMOUNT = 755
    TAX_EXEMPTION_REASON = 756
    TAX_EXEMPTION_REASON_CODE = 757
    TAX_INCLUDED_INDICATOR = 758
    TAX_INCLUSIVE_AMOUNT = 759
    TAX_LEVEL_CODE = 760
    TAX_POINT_DATE = 761
    TAX_TYPE_CODE = 762
    TAXABLE_AMOUNT = 763
    TECHNICAL_COMMITTEE_DESCRIPTION = 764
    TECHNICAL_NAME = 765
    TELECOMMUNICATIONS_SERVICE_CALL = 766
    TELECOMMUNICATIONS_SERVICE_CALL_CODE = 767
    TELECOMMUNICATIONS_SERVICE_CATEGORY = 768
    TELECOMMUNICATIONS_SERVICE_CATEGORY_CODE = 769
    TELECOMMUNICATIONS_SUPPLY_TYPE = 770
    TELECOMMUNICATIONS_SUPPLY_TYPE_CODE = 771
    TELEFAX = 772
    TELEPHONE = 773
    TENDER_ENVELOPE_ID = 774
    TENDER_ENVELOPE_TYPE_CODE = 775
    TENDER_RESULT_CODE = 776
    TENDER_TYPE_CODE = 777
    TENDERER_REQUIREMENT_TYPE_CODE = 778
    TENDERER_ROLE_CODE = 779
    TEST_METHOD = 780
    TEXT = 781
    THIRD_PARTY_PAYER_INDICATOR = 782
    THRESHOLD_AMOUNT = 783
    THRESHOLD_QUANTITY = 784
    THRESHOLD_VALUE_COMPARISON_CODE = 785
    TIER_RANGE = 786
    TIER_RATE_PERCENT = 787
    TIME_AMOUNT = 788
    TIME_DELTA_DAYS_QUANTITY = 789
    TIME_FREQUENCY_CODE = 790
    TIMEZONE_OFFSET = 791
    TIMING_COMPLAINT = 792
    TIMING_COMPLAINT_CODE = 793
    TITLE = 794
    TO_ORDER_INDICATOR = 795
    TOTAL_AMOUNT = 796
    TOTAL_BALANCE_AMOUNT = 797
    TOTAL_CONSUMED_QUANTITY = 798
    TOTAL_CREDIT_AMOUNT = 799
    TOTAL_DEBIT_AMOUNT = 800
    TOTAL_DELIVERED_QUANTITY = 801
    TOTAL_GOODS_ITEM_QUANTITY = 802
    TOTAL_INVOICE_AMOUNT = 803
    TOTAL_METERED_QUANTITY = 804
    TOTAL_PACKAGE_QUANTITY = 805
    TOTAL_PACKAGES_QUANTITY = 806
    TOTAL_PAYMENT_AMOUNT = 807
    TOTAL_TASK_AMOUNT = 808
    TOTAL_TAX_AMOUNT = 809
    TOTAL_TRANSPORT_HANDLING_UNIT_QUANTITY = 810
    TRACE_ID = 811
    TRACKING_DEVICE_CODE = 812
    TRACKING_ID = 813
    TRADE_ITEM_PACKING_LABELING_TYPE_CODE = 814
    TRADE_SERVICE_CODE = 815
    TRADING_RESTRICTIONS = 816
    TRAIN_ID = 817
    TRANSACTION_CURRENCY_TAX_AMOUNT = 818
    TRANSIT_DIRECTION_CODE = 819
    TRANSPORT_AUTHORIZATION_CODE = 820
    TRANSPORT_EMERGENCY_CARD_CODE = 821
    TRANSPORT_EQUIPMENT_TYPE_CODE = 822
    TRANSPORT_EVENT_TYPE_CODE = 823
    TRANSPORT_EXECUTION_PLAN_REFERENCE_ID = 824
    TRANSPORT_EXECUTION_STATUS_CODE = 825
    TRANSPORT_HANDLING_UNIT_TYPE_CODE = 826
    TRANSPORT_MEANS_TYPE_CODE = 827
    TRANSPORT_MODE_CODE = 828
    TRANSPORT_SERVICE_CODE = 829
    TRANSPORT_SERVICE_PROVIDER_REMARKS = 830
    TRANSPORT_SERVICE_PROVIDER_SPECIAL_TERMS = 831
    TRANSPORT_USER_REMARKS = 832
    TRANSPORT_USER_SPECIAL_TERMS = 833
    TRANSPORTATION_SERVICE_DESCRIPTION = 834
    TRANSPORTATION_SERVICE_DETAILS_URI = 835
    TRANSPORTATION_STATUS_TYPE_CODE = 836
    TYPE_CODE = 837
    UBL_VERSION_ID = 838
    U_N_D_G_CODE = 839
    URI = 840
    UUID = 841
    UNKNOWN_PRICE_INDICATOR = 842
    UPPER_ORANGE_HAZARD_PLACARD_ID = 843
    URGENCY_CODE = 844
    UTILITY_STATEMENT_TYPE_CODE = 845
    VALIDATE_PROCESS = 846
    VALIDATE_TOOL = 847
    VALIDATE_TOOL_VERSION = 848
    VALIDATION_DATE = 849
    VALIDATION_RESULT_CODE = 850
    VALIDATION_TIME = 851
    VALIDATOR_ID = 852
    VALIDITY_START_DATE = 853
    VALUE = 854
    VALUE_AMOUNT = 855
    VALUE_MEASURE = 856
    VALUE_QUALIFIER = 857
    VALUE_QUANTITY = 858
    VARIANCE_QUANTITY = 859
    VARIANT_CONSTRAINT_INDICATOR = 860
    VARIANT_ID = 861
    VERSION_ID = 862
    VESSEL_ID = 863
    VESSEL_NAME = 864
    WARRANTY_INFORMATION = 865
    WEBSITE_URI = 866
    WEEK_DAY_CODE = 867
    WEIGHT = 868
    WEIGHT_NUMERIC = 869
    WEIGHTING_ALGORITHM_CODE = 870
    WORK_PHASE = 871
    WORK_PHASE_CODE = 872
    XPATH = 873


@unique
class _AggregateBusinessInformationElementFlag(IntEnum):
    """
    List of the Aggregate Business Information Elements as defined in UBL 2.1
    """
    ACCEPTANCE_TRANSPORT_EVENT = 1
    ACCESSORY_RELATED_ITEM = 2
    ACCOUNTING_CONTACT = 3
    ACCOUNTING_CUSTOMER_PARTY = 4
    ACCOUNTING_SUPPLIER_PARTY = 5
    ACTIVITY_DATA_LINE = 6
    ACTIVITY_FINAL_LOCATION = 7
    ACTIVITY_ORIGIN_LOCATION = 8
    ACTIVITY_PERIOD = 9
    ACTIVITY_PROPERTY = 10
    ACTUAL_ARRIVAL_TRANSPORT_EVENT = 11
    ACTUAL_DEPARTURE_TRANSPORT_EVENT = 12
    ACTUAL_PACKAGE = 13
    ACTUAL_PICKUP_TRANSPORT_EVENT = 14
    ACTUAL_WAYPOINT_TRANSPORT_EVENT = 15
    ADDITIONAL_COMMODITY_CLASSIFICATION = 16
    ADDITIONAL_DOCUMENT_REFERENCE = 17
    ADDITIONAL_DOCUMENT_RESPONSE = 18
    ADDITIONAL_INFORMATION_PARTY = 19
    ADDITIONAL_ITEM_IDENTIFICATION = 20
    ADDITIONAL_ITEM_PROPERTY = 21
    ADDITIONAL_QUALIFYING_PARTY = 22
    ADDITIONAL_TEMPERATURE = 23
    ADDITIONAL_TRANSPORTATION_SERVICE = 24
    ADDRESS = 25
    ADDRESS_LINE = 26
    AGENT_PARTY = 27
    AIR_TRANSPORT = 28
    ALLOWANCE_CHARGE = 29
    ALLOWED_SUBCONTRACT_TERMS = 30
    ALTERNATIVE_CONDITION_PRICE = 31
    ALTERNATIVE_DELIVERY_LOCATION = 32
    ALTERNATIVE_LINE_ITEM = 33
    ANTICIPATED_MONETARY_TOTAL = 34
    APPEAL_INFORMATION_PARTY = 35
    APPEAL_RECEIVER_PARTY = 36
    APPEAL_TERMS = 37
    APPLICABLE_ADDRESS = 38
    APPLICABLE_PERIOD = 39
    APPLICABLE_REGULATION = 40
    APPLICABLE_TAX_CATEGORY = 41
    APPLICABLE_TERRITORY_ADDRESS = 42
    APPLICABLE_TRANSPORT_MEANS = 43
    AT_LOCATION = 44
    ATTACHED_TRANSPORT_EQUIPMENT = 45
    ATTACHMENT = 46
    AUCTION_TERMS = 47
    AVAILABILITY_TRANSPORT_EVENT = 48
    AWARDED_TENDERED_PROJECT = 49
    AWARDING_CRITERION = 50
    AWARDING_CRITERION_RESPONSE = 51
    AWARDING_TERMS = 52
    BENEFICIARY_PARTY = 53
    BILL_OF_LADING_HOLDER_PARTY = 54
    BILL_TO_PARTY = 55
    BILLING_REFERENCE = 56
    BILLING_REFERENCE_LINE = 57
    BONUS_PAYMENT_TERMS = 58
    BRANCH = 59
    BUDGET_ACCOUNT = 60
    BUDGET_ACCOUNT_LINE = 61
    BUSINESS_CLASSIFICATION_SCHEME = 62
    BUYER_CONTACT = 63
    BUYER_CUSTOMER_PARTY = 64
    BUYER_PROPOSED_SUBSTITUTE_LINE_ITEM = 65
    BUYERS_ITEM_IDENTIFICATION = 66
    CALL_DUTY = 67
    CALL_FOR_TENDERS_DOCUMENT_REFERENCE = 68
    CALL_FOR_TENDERS_LINE_REFERENCE = 69
    CAPABILITY = 70
    CARD_ACCOUNT = 71
    CARRIER_PARTY = 72
    CATALOGUE_DOCUMENT_REFERENCE = 73
    CATALOGUE_ITEM_IDENTIFICATION = 74
    CATALOGUE_ITEM_SPECIFICATION_UPDATE_LINE = 75
    CATALOGUE_LINE = 76
    CATALOGUE_LINE_REFERENCE = 77
    CATALOGUE_PRICING_UPDATE_LINE = 78
    CATALOGUE_REFERENCE = 79
    CATALOGUE_REQUEST_LINE = 80
    CATEGORIZES_CLASSIFICATION_CATEGORY = 81
    CERTIFICATE = 82
    CERTIFICATE_OF_ORIGIN_APPLICATION = 83
    CHILD_CONSIGNMENT = 84
    CLASSIFICATION_CATEGORY = 85
    CLASSIFICATION_SCHEME = 86
    CLASSIFIED_TAX_CATEGORY = 87
    CLAUSE = 88
    COLLECT_PAYMENT_TERMS = 89
    COLLECTED_PAYMENT = 90
    COMMISSION_PAYMENT_TERMS = 91
    COMMODITY_CLASSIFICATION = 92
    COMMUNICATION = 93
    COMPLEMENTARY_RELATED_ITEM = 94
    COMPLETED_TASK = 95
    COMPONENT_RELATED_ITEM = 96
    CONDITION = 97
    CONSIGNEE_PARTY = 98
    CONSIGNMENT = 99
    CONSIGNOR_PARTY = 100
    CONSOLIDATED_SHIPMENT = 101
    CONSTITUTION_PERIOD = 102
    CONSUMPTION = 103
    CONSUMPTION_AVERAGE = 104
    CONSUMPTION_CORRECTION = 105
    CONSUMPTION_HISTORY = 106
    CONSUMPTION_LINE = 107
    CONSUMPTION_POINT = 108
    CONSUMPTION_REPORT = 109
    CONSUMPTION_REPORT_REFERENCE = 110
    CONTACT = 111
    CONTACT_PARTY = 112
    CONTAINED_GOODS_ITEM = 113
    CONTAINED_IN_TRANSPORT_EQUIPMENT = 114
    CONTAINED_PACKAGE = 115
    CONTAINING_PACKAGE = 116
    CONTAINING_TRANSPORT_EQUIPMENT = 117
    CONTRACT = 118
    CONTRACT_ACCEPTANCE_PERIOD = 119
    CONTRACT_DOCUMENT_REFERENCE = 120
    CONTRACT_EXECUTION_REQUIREMENT = 121
    CONTRACT_EXTENSION = 122
    CONTRACT_FORMALIZATION_PERIOD = 123
    CONTRACT_RESPONSIBLE_PARTY = 124
    CONTRACTING_ACTIVITY = 125
    CONTRACTING_PARTY = 126
    CONTRACTING_PARTY_TYPE = 127
    CONTRACTOR_CUSTOMER_PARTY = 128
    CONTRACTUAL_DELIVERY = 129
    CONTRACTUAL_DOCUMENT_REFERENCE = 130
    CORPORATE_REGISTRATION_SCHEME = 131
    COUNTRY = 132
    CREDIT_ACCOUNT = 133
    CREDIT_NOTE_DOCUMENT_REFERENCE = 134
    CREDIT_NOTE_LINE = 135
    CREW_MEMBER_PERSON = 136
    CURRENT_STATUS = 137
    CUSTOMER_PARTY = 138
    CUSTOMS_AGENT_PARTY = 139
    CUSTOMS_DECLARATION = 140
    DEBIT_NOTE_DOCUMENT_REFERENCE = 141
    DEBIT_NOTE_LINE = 142
    DECLARATION = 143
    DEFAULT_LANGUAGE = 144
    DELETED_CATALOGUE_REFERENCE = 145
    DELIVERY = 146
    DELIVERY_ADDRESS = 147
    DELIVERY_CONTACT = 148
    DELIVERY_CUSTOMER_PARTY = 149
    DELIVERY_LOCATION = 150
    DELIVERY_PARTY = 151
    DELIVERY_PERIOD = 152
    DELIVERY_TERMS = 153
    DELIVERY_TRANSPORT_EVENT = 154
    DELIVERY_UNIT = 155
    DEPENDENT_LINE_REFERENCE = 156
    DEPENDENT_PRICE_REFERENCE = 157
    DESPATCH = 158
    DESPATCH_ADDRESS = 159
    DESPATCH_CONTACT = 160
    DESPATCH_DOCUMENT_REFERENCE = 161
    DESPATCH_LINE = 162
    DESPATCH_LINE_REFERENCE = 163
    DESPATCH_LOCATION = 164
    DESPATCH_PARTY = 165
    DESPATCH_SUPPLIER_PARTY = 166
    DESTINATION_COUNTRY = 167
    DETENTION_TRANSPORT_EVENT = 168
    DIGITAL_SIGNATURE_ATTACHMENT = 169
    DIMENSION = 170
    DISBURSEMENT_PAYMENT_TERMS = 171
    DISCHARGE_TRANSPORT_EVENT = 172
    DISCREPANCY_RESPONSE = 173
    DOCUMENT_AVAILABILITY_PERIOD = 174
    DOCUMENT_DISTRIBUTION = 175
    DOCUMENT_PROVIDER_PARTY = 176
    DOCUMENT_REFERENCE = 177
    DOCUMENT_RESPONSE = 178
    DOCUMENT_TENDER_REQUIREMENT = 179
    DRIVER_PERSON = 180
    DROPOFF_TRANSPORT_EVENT = 181
    DURATION_PERIOD = 182
    DUTY = 183
    ECONOMIC_OPERATOR_ROLE = 184
    ECONOMIC_OPERATOR_SHORT_LIST = 185
    EFFECTIVE_PERIOD = 186
    EMBASSY_ENDORSEMENT = 187
    EMERGENCY_TEMPERATURE = 188
    EMISSION_CALCULATION_METHOD = 189
    EMPLOYMENT_LEGISLATION_DOCUMENT_REFERENCE = 190
    ENDORSEMENT = 191
    ENDORSER_PARTY = 192
    ENERGY_TAX_REPORT = 193
    ENERGY_WATER_CONSUMPTION_CORRECTION = 194
    ENERGY_WATER_SUPPLY = 195
    ENVIRONMENTAL_EMISSION = 196
    ENVIRONMENTAL_LEGISLATION_DOCUMENT_REFERENCE = 197
    ESTIMATED_ARRIVAL_TRANSPORT_EVENT = 198
    ESTIMATED_DELIVERY_PERIOD = 199
    ESTIMATED_DEPARTURE_TRANSPORT_EVENT = 200
    ESTIMATED_DESPATCH_PERIOD = 201
    ESTIMATED_DURATION_PERIOD = 202
    ESTIMATED_TRANSIT_PERIOD = 203
    EVALUATION_CRITERION = 204
    EVENT = 205
    EVENT_COMMENT = 206
    EVENT_LINE_ITEM = 207
    EVENT_TACTIC = 208
    EVENT_TACTIC_ENUMERATION = 209
    EVIDENCE = 210
    EVIDENCE_DOCUMENT_REFERENCE = 211
    EVIDENCE_ISSUING_PARTY = 212
    EVIDENCE_SUPPLIED = 213
    EXAMINATION_TRANSPORT_EVENT = 214
    EXCEPTION_CRITERIA_LINE = 215
    EXCEPTION_NOTIFICATION_LINE = 216
    EXCEPTION_OBSERVATION_PERIOD = 217
    EXCHANGE_RATE = 218
    EXPORT_COUNTRY = 219
    EXPORTATION_TRANSPORT_EVENT = 220
    EXPORTER_PARTY = 221
    EXTERNAL_REFERENCE = 222
    EXTRA_ALLOWANCE_CHARGE = 223
    FINAL_DELIVERY_PARTY = 224
    FINAL_DELIVERY_TRANSPORTATION_SERVICE = 225
    FINAL_DESTINATION_COUNTRY = 226
    FINAL_FINANCIAL_GUARANTEE = 227
    FINANCIAL_ACCOUNT = 228
    FINANCIAL_CAPABILITY = 229
    FINANCIAL_EVALUATION_CRITERION = 230
    FINANCIAL_GUARANTEE = 231
    FINANCIAL_INSTITUTION = 232
    FINANCIAL_INSTITUTION_BRANCH = 233
    FINANCING_FINANCIAL_ACCOUNT = 234
    FINANCING_PARTY = 235
    FIRST_ARRIVAL_PORT_LOCATION = 236
    FISCAL_LEGISLATION_DOCUMENT_REFERENCE = 237
    FLASHPOINT_TEMPERATURE = 238
    FLOOR_SPACE_MEASUREMENT_DIMENSION = 239
    FORECAST_EXCEPTION = 240
    FORECAST_EXCEPTION_CRITERION_LINE = 241
    FORECAST_LINE = 242
    FORECAST_PERIOD = 243
    FORECAST_REVISION_LINE = 244
    FOREIGN_EXCHANGE_CONTRACT = 245
    FRAMEWORK_AGREEMENT = 246
    FREIGHT_ALLOWANCE_CHARGE = 247
    FREIGHT_CHARGE_LOCATION = 248
    FREIGHT_FORWARDER_PARTY = 249
    FREQUENCY_PERIOD = 250
    FROM_LOCATION = 251
    GOODS_ITEM = 252
    GOODS_ITEM_CONTAINER = 253
    GUARANTEE_DOCUMENT_REFERENCE = 254
    GUARANTOR_PARTY = 255
    GUIDANCE_DOCUMENT_REFERENCE = 256
    HANDLING_TRANSPORT_EVENT = 257
    HANDLING_UNIT_DESPATCH_LINE = 258
    HAULAGE_TRADING_TERMS = 259
    HAZARDOUS_GOODS_TRANSIT = 260
    HAZARDOUS_ITEM = 261
    HAZARDOUS_ITEM_NOTIFICATION_PARTY = 262
    HEAD_OFFICE_PARTY = 263
    IDENTITY_DOCUMENT_REFERENCE = 264
    IMMOBILIZED_SECURITY = 265
    IMPORTER_PARTY = 266
    INFORMATION_CONTENT_PROVIDER_PARTY = 267
    INSTRUCTION_FOR_RETURNS_LINE = 268
    INSURANCE_ENDORSEMENT = 269
    INSURANCE_PARTY = 270
    INTERESTED_PARTY = 271
    INTERESTED_PROCUREMENT_PROJECT_LOT = 272
    INVENTORY_LOCATION = 273
    INVENTORY_PERIOD = 274
    INVENTORY_REPORT_LINE = 275
    INVENTORY_REPORTING_PARTY = 276
    INVITATION_SUBMISSION_PERIOD = 277
    INVOICE_DOCUMENT_REFERENCE = 278
    INVOICE_LINE = 279
    INVOICE_PERIOD = 280
    ISSUER_ENDORSEMENT = 281
    ISSUER_PARTY = 282
    ISSUING_COUNTRY = 283
    ITEM = 284
    ITEM_COMPARISON = 285
    ITEM_IDENTIFICATION = 286
    ITEM_INFORMATION_REQUEST_LINE = 287
    ITEM_INSTANCE = 288
    ITEM_LOCATION_QUANTITY = 289
    ITEM_MANAGEMENT_PROFILE = 290
    ITEM_PRICE_EXTENSION = 291
    ITEM_PROPERTY = 292
    ITEM_PROPERTY_GROUP = 293
    ITEM_PROPERTY_RANGE = 294
    ITEM_SPECIFICATION_DOCUMENT_REFERENCE = 295
    JURISDICTION_REGION_ADDRESS = 296
    KEYWORD_ITEM_PROPERTY = 297
    LANGUAGE = 298
    LAST_EXIT_PORT_LOCATION = 299
    LEGAL_DOCUMENT_REFERENCE = 300
    LEGAL_MONETARY_TOTAL = 301
    LINE_ITEM = 302
    LINE_REFERENCE = 303
    LINE_RESPONSE = 304
    LINE_VALIDITY_PERIOD = 305
    LOADING_LOCATION = 306
    LOADING_PORT_LOCATION = 307
    LOADING_PROOF_PARTY = 308
    LOADING_TRANSPORT_EVENT = 309
    LOCATION = 310
    LOCATION_ADDRESS = 311
    LOCATION_COORDINATE = 312
    LOGISTICS_OPERATOR_PARTY = 313
    LOT_IDENTIFICATION = 314
    MAIN_CARRIAGE_SHIPMENT_STAGE = 315
    MAIN_COMMODITY_CLASSIFICATION = 316
    MAIN_ON_ACCOUNT_PAYMENT = 317
    MAIN_PERIOD = 318
    MAIN_QUALIFYING_PARTY = 319
    MAIN_TRANSPORTATION_SERVICE = 320
    MANDATE_DOCUMENT_REFERENCE = 321
    MANUFACTURER_PARTY = 322
    MANUFACTURERS_ITEM_IDENTIFICATION = 323
    MARITIME_TRANSPORT = 324
    MASTER_PERSON = 325
    MAXIMUM_DELIVERY_UNIT = 326
    MAXIMUM_TEMPERATURE = 327
    MEASUREMENT_DIMENSION = 328
    MEASUREMENT_FROM_LOCATION = 329
    MEASUREMENT_TO_LOCATION = 330
    MEDIATION_PARTY = 331
    METER = 332
    METER_PROPERTY = 333
    METER_READING = 334
    MINIMUM_DELIVERY_UNIT = 335
    MINIMUM_TEMPERATURE = 336
    MINUTES_DOCUMENT_REFERENCE = 337
    MISCELLANEOUS_EVENT = 338
    MONETARY_TOTAL = 339
    MORTGAGE_HOLDER_PARTY = 340
    NOMINATION_PERIOD = 341
    NOTARY_PARTY = 342
    NOTICE_DOCUMENT_REFERENCE = 343
    NOTIFICATION_LOCATION = 344
    NOTIFICATION_PERIOD = 345
    NOTIFICATION_REQUIREMENT = 346
    NOTIFY_PARTY = 347
    OCCURENCE_LOCATION = 348
    OFFERED_ITEM_LOCATION_QUANTITY = 349
    ON_ACCOUNT_PAYMENT = 350
    ON_CARRIAGE_SHIPMENT_STAGE = 351
    OPEN_TENDER_EVENT = 352
    OPERATING_PARTY = 353
    OPTION_VALIDITY_PERIOD = 354
    OPTIONAL_TAKEOVER_TRANSPORT_EVENT = 355
    ORDER_DOCUMENT_REFERENCE = 356
    ORDER_LINE = 357
    ORDER_LINE_REFERENCE = 358
    ORDER_REFERENCE = 359
    ORDERED_SHIPMENT = 360
    ORIGIN_ADDRESS = 361
    ORIGIN_COUNTRY = 362
    ORIGINAL_DEPARTURE_COUNTRY = 363
    ORIGINAL_DESPATCH_PARTY = 364
    ORIGINAL_DESPATCH_TRANSPORTATION_SERVICE = 365
    ORIGINAL_DOCUMENT_REFERENCE = 366
    ORIGINAL_ITEM_LOCATION_QUANTITY = 367
    ORIGINATOR_CUSTOMER_PARTY = 368
    ORIGINATOR_DOCUMENT_REFERENCE = 369
    ORIGINATOR_PARTY = 370
    OTHER_COMMUNICATION = 371
    OWNER_PARTY = 372
    PACKAGE = 373
    PACKAGED_TRANSPORT_HANDLING_UNIT = 374
    PALLET_SPACE_MEASUREMENT_DIMENSION = 375
    PARENT_DOCUMENT_LINE_REFERENCE = 376
    PARENT_DOCUMENT_REFERENCE = 377
    PARTICIPATING_LOCATIONS_LOCATION = 378
    PARTICIPATION_REQUEST_RECEPTION_PERIOD = 379
    PARTY = 380
    PARTY_IDENTIFICATION = 381
    PARTY_LEGAL_ENTITY = 382
    PARTY_NAME = 383
    PARTY_TAX_SCHEME = 384
    PASSENGER_PERSON = 385
    PAYEE_FINANCIAL_ACCOUNT = 386
    PAYEE_PARTY = 387
    PAYER_FINANCIAL_ACCOUNT = 388
    PAYER_PARTY = 389
    PAYMENT = 390
    PAYMENT_ALTERNATIVE_EXCHANGE_RATE = 391
    PAYMENT_EXCHANGE_RATE = 392
    PAYMENT_MANDATE = 393
    PAYMENT_MEANS = 394
    PAYMENT_REVERSAL_PERIOD = 395
    PAYMENT_TERMS = 396
    PENALTY_CLAUSE = 397
    PENALTY_PAYMENT_TERMS = 398
    PENALTY_PERIOD = 399
    PERFORMANCE_DATA_LINE = 400
    PERFORMING_CARRIER_PARTY = 401
    PERIOD = 402
    PERSON = 403
    PHYSICAL_ATTRIBUTE = 404
    PHYSICAL_LOCATION = 405
    PICKUP = 406
    PICKUP_LOCATION = 407
    PICKUP_PARTY = 408
    PICKUP_TRANSPORT_EVENT = 409
    PLANNED_ARRIVAL_TRANSPORT_EVENT = 410
    PLANNED_DELIVERY_TRANSPORT_EVENT = 411
    PLANNED_DEPARTURE_TRANSPORT_EVENT = 412
    PLANNED_PERIOD = 413
    PLANNED_PICKUP_TRANSPORT_EVENT = 414
    PLANNED_WAYPOINT_TRANSPORT_EVENT = 415
    POSITIONING_TRANSPORT_EVENT = 416
    POSTAL_ADDRESS = 417
    POWER_OF_ATTORNEY = 418
    PRE_CARRIAGE_SHIPMENT_STAGE = 419
    PRE_SELECTED_PARTY = 420
    PREPAID_PAYMENT = 421
    PREPAID_PAYMENT_TERMS = 422
    PREPARATION_PARTY = 423
    PRESENTATION_PERIOD = 424
    PREVIOUS_DOCUMENT_REFERENCE = 425
    PREVIOUS_PRICE_LIST = 426
    PRICE = 427
    PRICE_EXTENSION = 428
    PRICE_LIST = 429
    PRICING_EXCHANGE_RATE = 430
    PRICING_REFERENCE = 431
    PROCESS_JUSTIFICATION = 432
    PROCUREMENT_LEGISLATION_DOCUMENT_REFERENCE = 433
    PROCUREMENT_PROJECT = 434
    PROCUREMENT_PROJECT_LOT = 435
    PROJECT_REFERENCE = 436
    PROMISED_DELIVERY_PERIOD = 437
    PROMOTIONAL_EVENT = 438
    PROMOTIONAL_EVENT_LINE_ITEM = 439
    PROMOTIONAL_SPECIFICATION = 440
    PROVIDER_PARTY = 441
    QUALIFICATION_RESOLUTION = 442
    QUALIFYING_PARTY = 443
    QUARANTINE_TRANSPORT_EVENT = 444
    QUOTATION_DOCUMENT_REFERENCE = 445
    QUOTATION_LINE = 446
    QUOTATION_LINE_REFERENCE = 447
    QUOTED_MONETARY_TOTAL = 448
    RAIL_TRANSPORT = 449
    RANGE_DIMENSION = 450
    REALIZED_LOCATION = 451
    RECEIPT_DOCUMENT_REFERENCE = 452
    RECEIPT_LINE = 453
    RECEIPT_LINE_REFERENCE = 454
    RECEIPT_TRANSPORT_EVENT = 455
    RECEIVED_HANDLING_UNIT_RECEIPT_LINE = 456
    RECEIVER_PARTY = 457
    RECIPIENT_CUSTOMER_PARTY = 458
    RECIPIENT_PARTY = 459
    REFERENCED_CONSIGNMENT = 460
    REFERENCED_CONTRACT = 461
    REFERENCED_GOODS_ITEM = 462
    REFERENCED_PACKAGE = 463
    REFERENCED_SHIPMENT = 464
    REFERENCED_TRANSPORT_EQUIPMENT = 465
    REGISTRATION_ADDRESS = 466
    REGISTRY_CERTIFICATE_DOCUMENT_REFERENCE = 467
    REGISTRY_PORT_LOCATION = 468
    REGULATION = 469
    RELATED_CATALOGUE_REFERENCE = 470
    RELATED_ITEM = 471
    REMINDER_DOCUMENT_REFERENCE = 472
    REMINDER_LINE = 473
    REMINDER_PERIOD = 474
    REMITTANCE_ADVICE_LINE = 475
    RENEWAL = 476
    REPLACED_NOTICE_DOCUMENT_REFERENCE = 477
    REPLACED_RELATED_ITEM = 478
    REPLACEMENT_RELATED_ITEM = 479
    REPORTED_SHIPMENT = 480
    REPORTING_PERSON = 481
    REQUEST_FOR_QUOTATION_DOCUMENT_REFERENCE = 482
    REQUEST_FOR_QUOTATION_LINE = 483
    REQUEST_FOR_TENDER_LINE = 484
    REQUEST_LINE_REFERENCE = 485
    REQUESTED_ARRIVAL_TRANSPORT_EVENT = 486
    REQUESTED_CATALOGUE_REFERENCE = 487
    REQUESTED_CLASSIFICATION_SCHEME = 488
    REQUESTED_DELIVERY_PERIOD = 489
    REQUESTED_DELIVERY_TRANSPORT_EVENT = 490
    REQUESTED_DEPARTURE_TRANSPORT_EVENT = 491
    REQUESTED_DESPATCH_PERIOD = 492
    REQUESTED_DOCUMENT_REFERENCE = 493
    REQUESTED_LANGUAGE = 494
    REQUESTED_MONETARY_TOTAL = 495
    REQUESTED_PICKUP_TRANSPORT_EVENT = 496
    REQUESTED_STATUS_LOCATION = 497
    REQUESTED_STATUS_PERIOD = 498
    REQUESTED_TENDER_TOTAL = 499
    REQUESTED_VALIDITY_PERIOD = 500
    REQUESTED_WAYPOINT_TRANSPORT_EVENT = 501
    REQUIRED_BUSINESS_CLASSIFICATION_SCHEME = 502
    REQUIRED_CLASSIFICATION_SCHEME = 503
    REQUIRED_FINANCIAL_GUARANTEE = 504
    REQUIRED_ITEM_LOCATION_QUANTITY = 505
    REQUIRED_RELATED_ITEM = 506
    RESIDENCE_ADDRESS = 507
    RESOLUTION_DOCUMENT_REFERENCE = 508
    RESPONSE = 509
    RESPONSIBLE_TRANSPORT_SERVICE_PROVIDER_PARTY = 510
    RESULT_OF_VERIFICATION = 511
    RETAIL_PLANNED_IMPACT = 512
    RETAILER_CUSTOMER_PARTY = 513
    RETURN_ADDRESS = 514
    ROAD_TRANSPORT = 515
    SALES_ITEM = 516
    SCHEDULED_SERVICE_FREQUENCY = 517
    SECONDARY_HAZARD = 518
    SECURITY_OFFICER_PERSON = 519
    SELF_BILLED_CREDIT_NOTE_DOCUMENT_REFERENCE = 520
    SELF_BILLED_INVOICE_DOCUMENT_REFERENCE = 521
    SELLER_CONTACT = 522
    SELLER_PROPOSED_SUBSTITUTE_LINE_ITEM = 523
    SELLER_SUBSTITUTED_LINE_ITEM = 524
    SELLER_SUPPLIER_PARTY = 525
    SELLERS_ITEM_IDENTIFICATION = 526
    SENDER_PARTY = 527
    SERVICE_ALLOWANCE_CHARGE = 528
    SERVICE_CHARGE_PAYMENT_TERMS = 529
    SERVICE_END_TIME_PERIOD = 530
    SERVICE_FREQUENCY = 531
    SERVICE_PROVIDER_PARTY = 532
    SERVICE_START_TIME_PERIOD = 533
    SETTLEMENT_PERIOD = 534
    SHAREHOLDER_PARTY = 535
    SHIPMENT = 536
    SHIPMENT_DOCUMENT_REFERENCE = 537
    SHIPMENT_STAGE = 538
    SHIPS_SURGEON_PERSON = 539
    SIGNATORY_CONTACT = 540
    SIGNATORY_PARTY = 541
    SIGNATURE = 542
    SOURCE_CATALOGUE_REFERENCE = 543
    SOURCE_ISSUER_PARTY = 544
    SPECIFIC_TENDERER_REQUIREMENT = 545
    STANDARD_ITEM_IDENTIFICATION = 546
    STATEMENT_DOCUMENT_REFERENCE = 547
    STATEMENT_LINE = 548
    STATEMENT_PERIOD = 549
    STATUS = 550
    STATUS_LOCATION = 551
    STATUS_PERIOD = 552
    STOCK_AVAILABILITY_REPORT_LINE = 553
    STORAGE_LOCATION = 554
    STORAGE_TRANSPORT_EVENT = 555
    STOWAGE = 556
    SUB_CREDIT_NOTE_LINE = 557
    SUB_DEBIT_NOTE_LINE = 558
    SUB_INVOICE_LINE = 559
    SUB_LINE_ITEM = 560
    SUB_REQUEST_FOR_TENDER_LINE = 561
    SUB_TENDER_LINE = 562
    SUBCONTRACT_TERMS = 563
    SUBCONTRACTOR_PARTY = 564
    SUBORDINATE_AWARDING_CRITERION = 565
    SUBORDINATE_AWARDING_CRITERION_RESPONSE = 566
    SUBSCRIBER_CONSUMPTION = 567
    SUBSCRIBER_PARTY = 568
    SUBSEQUENT_PROCESS_TENDER_REQUIREMENT = 569
    SUBSIDIARY_LOCATION = 570
    SUBSTITUTE_CARRIER_PARTY = 571
    SUGGESTED_EVIDENCE = 572
    SUPPLIER_CONSUMPTION = 573
    SUPPLIER_PARTY = 574
    SUPPLY_CHAIN_ACTIVITY_DATA_LINE = 575
    SUPPLY_ITEM = 576
    SUPPORTED_COMMODITY_CLASSIFICATION = 577
    SUPPORTED_TRANSPORT_EQUIPMENT = 578
    SUPPORTING_DOCUMENT_REFERENCE = 579
    TAKEOVER_TRANSPORT_EVENT = 580
    TAX_CATEGORY = 581
    TAX_EXCHANGE_RATE = 582
    TAX_EXCLUSIVE_PRICE = 583
    TAX_INCLUSIVE_PRICE = 584
    TAX_REPRESENTATIVE_PARTY = 585
    TAX_SCHEME = 586
    TAX_SUBTOTAL = 587
    TAX_TOTAL = 588
    TECHNICAL_CAPABILITY = 589
    TECHNICAL_COMMITTEE_PERSON = 590
    TECHNICAL_DOCUMENT_REFERENCE = 591
    TECHNICAL_EVALUATION_CRITERION = 592
    TELECOMMUNICATIONS_SERVICE = 593
    TELECOMMUNICATIONS_SUPPLY = 594
    TELECOMMUNICATIONS_SUPPLY_LINE = 595
    TEMPERATURE = 596
    TEMPLATE_DOCUMENT_REFERENCE = 597
    TENDER_DOCUMENT_REFERENCE = 598
    TENDER_EVALUATION_PARTY = 599
    TENDER_LINE = 600
    TENDER_PREPARATION = 601
    TENDER_RECIPIENT_PARTY = 602
    TENDER_REQUIREMENT = 603
    TENDER_RESULT = 604
    TENDER_SUBMISSION_DEADLINE_PERIOD = 605
    TENDER_VALIDITY_PERIOD = 606
    TENDERED_PROJECT = 607
    TENDERER_PARTY = 608
    TENDERER_PARTY_QUALIFICATION = 609
    TENDERER_QUALIFICATION_DOCUMENT_REFERENCE = 610
    TENDERER_QUALIFICATION_REQUEST = 611
    TENDERER_REQUIREMENT = 612
    TENDERING_PROCESS = 613
    TENDERING_TERMS = 614
    TERMINAL_OPERATOR_PARTY = 615
    TIME_DUTY = 616
    TO_LOCATION = 617
    TOTAL_CAPACITY_DIMENSION = 618
    TRADE_FINANCING = 619
    TRADING_TERMS = 620
    TRANSACTION_CONDITIONS = 621
    TRANSIT_COUNTRY = 622
    TRANSIT_PERIOD = 623
    TRANSPORT_ADVISOR_PARTY = 624
    TRANSPORT_CONTRACT = 625
    TRANSPORT_EQUIPMENT = 626
    TRANSPORT_EQUIPMENT_SEAL = 627
    TRANSPORT_EVENT = 628
    TRANSPORT_EXECUTION_PLAN_DOCUMENT_REFERENCE = 629
    TRANSPORT_EXECUTION_PLAN_REQUEST_DOCUMENT_REFERENCE = 630
    TRANSPORT_EXECUTION_TERMS = 631
    TRANSPORT_HANDLING_UNIT = 632
    TRANSPORT_MEANS = 633
    TRANSPORT_PROGRESS_STATUS_REQUEST_DOCUMENT_REFERENCE = 634
    TRANSPORT_SCHEDULE = 635
    TRANSPORT_SERVICE_DESCRIPTION_DOCUMENT_REFERENCE = 636
    TRANSPORT_SERVICE_DESCRIPTION_REQUEST_DOCUMENT_REFERENCE = 637
    TRANSPORT_SERVICE_PROVIDER_PARTY = 638
    TRANSPORT_SERVICE_PROVIDER_RESPONSE_DEADLINE_PERIOD = 639
    TRANSPORT_SERVICE_PROVIDER_RESPONSE_REQUIRED_PERIOD = 640
    TRANSPORT_USER_PARTY = 641
    TRANSPORT_USER_RESPONSE_REQUIRED_PERIOD = 642
    TRANSPORTATION_SEGMENT = 643
    TRANSPORTATION_SERVICE = 644
    TRANSPORTATION_STATUS_REQUEST_DOCUMENT_REFERENCE = 645
    TRANSSHIP_PORT_LOCATION = 646
    UNLOADING_LOCATION = 647
    UNLOADING_PORT_LOCATION = 648
    UNSTRUCTURED_PRICE = 649
    UNSUPPORTED_COMMODITY_CLASSIFICATION = 650
    UNSUPPORTED_TRANSPORT_EQUIPMENT = 651
    UPDATED_DELIVERY_TRANSPORT_EVENT = 652
    UPDATED_PICKUP_TRANSPORT_EVENT = 653
    USABILITY_PERIOD = 654
    UTILITY_CONSUMPTION_POINT = 655
    UTILITY_CUSTOMER_PARTY = 656
    UTILITY_ITEM = 657
    UTILITY_METER = 658
    UTILITY_SUPPLIER_PARTY = 659
    VALIDITY_PERIOD = 660
    WAREHOUSING_TRANSPORT_EVENT = 661
    WARRANTY_PARTY = 662
    WARRANTY_VALIDITY_PERIOD = 663
    WEB_SITE_ACCESS = 664
    WINNING_PARTY = 665
    WITHHOLDING_TAX_TOTAL = 666
    WITNESS_PARTY = 667
    WORK_ORDER_DOCUMENT_REFERENCE = 668
    WORK_PHASE_REFERENCE = 669


@unique
class _BusinessDocumentFlag(IntEnum):
    """
    Defines a list of named constants which identifies all
    Business Documents supported by this Python implementation of UBL 2.1
    """
    APPLICATION_RESPONSE = 2
    ATTACHED_DOCUMENT = 3
    UNAWARDED_NOTIFICATION = 5
    BILL_OF_LADING = 7
    CALL_FOR_TENDERS = 11
    CATALOGUE = 13
    CATALOGUE_DELETION = 17
    CATALOGUE_ITEM_SPECIFICATION_UPDATE = 19
    CATALOGUE_PRICING_UPDATE = 23
    CATALOGUE_REQUEST = 29
    CERTIFICATE_OF_ORIGIN = 31
    CONTRACT_AWARD_NOTICE = 37
    CONTRACT_NOTICE = 41
    CREDIT_NOTE = 43
    DEBIT_NOTE = 47
    DESPATCH_ADVICE = 53
    DOCUMENT_STATUS = 59
    DOCUMENT_STATUS_REQUEST = 61
    EXCEPTION_CRITERIA = 67
    EXCEPTION_NOTIFICATION = 71
    FORECAST = 73
    FORECAST_REVISION = 79
    FORWARDING_INSTRUCTIONS = 83
    FREIGHT_INVOICE = 89
    FULFILMENT_CANCELLATION = 97
    GOODS_ITEM_ITINERARY = 101
    GUARANTEE_CERTIFICATE = 103
    INSTRUCTION_FOR_RETURNS = 107
    INVENTORY_REPORT = 109
    INVOICE = 113
    ITEM_INFORMATION_REQUEST = 127
    ORDER = 131
    ORDER_CANCELLATION = 137
    ORDER_CHANGE = 139
    ORDER_RESPONSE = 149
    ORDER_RESPONSE_SIMPLE = 151
    PACKING_LIST = 157
    PRIOR_INFORMATION_NOTICE = 163
    PRODUCT_ACTIVITY = 167
    QUOTATION = 173
    RECEIPT_ADVICE = 179
    REMINDER = 181
    REMITTANCE_ADVICE = 191
    REQUEST_FOR_QUOTATION = 193
    RETAIL_EVENT = 197
    SELF_BILLED_CREDIT_NOTE = 199
    SELF_BILLED_INVOICE = 211
    STATEMENT = 223
    STOCK_AVAILABILITY_REPORT = 227
    TENDER = 229
    TENDERER_QUALIFICATION = 233
    TENDERER_QUALIFICATION_RESPONSE = 239
    TENDER_RECEIPT = 241
    TRADE_ITEM_LOCATION_PROFILE = 251
    TRANSPORTATION_STATUS = 257
    TRANSPORTATION_STATUS_REQUEST = 263
    TRANSPORT_EXECUTION_PLAN = 269
    TRANSPORT_EXECUTION_PLAN_REQUEST = 271
    TRANSPORT_PROGRESS_STATUS = 277
    TRANSPORT_PROGRESS_STATUS_REQUEST = 281
    TRANSPORT_SERVICE_DESCRIPTION = 283
    TRANSPORT_SERVICE_DESCRIPTION_REQUEST = 293
    UTILITY_STATEMENT = 307
    WAYBILL = 311


class DocumentDescriptor:
    _fields = None

    def __get__(self, instance, owner):
        try:
            if hasattr(instance, '_fields') or hasattr(owner, '_fields'):
                return self._fields
        except KeyError:
            raise KeyError(
                'Document definition does not exit in '
                'current UBL 2.1 specification'
            )

    def __set__(self, instance, value):
        raise AttributeError('Cannot modify attribute')

    def __del__(self):
        raise AttributeError('Cannot delete attribute')


class ApplicationResponse(DocumentDescriptor):
    def __init__(self):
        self._fields = (
            'application_response',
            'ubl_version_id',
            'customization_id',
            'profile_id',
            'profile_execution_id',
            'id',
            'uuid',
            'issue_date',
            'issue_time',
            'response_date',
            'response_time',
            'note',
            'version_id',
            'signature',
            'sender_party',
            'receiver_party',
            'document_response',
        )


class AttachedDocument(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class UnawardedNotification(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class BillOfLading(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class CallForTenders(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class Catalogue(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class CatalogueDeletion(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class CatalogueItemSpecificationUpdate(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class CataloguePricingUpdate(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class CatalogueRequest(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class CertificateOfOrigin(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class ContractAwardNotice(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class ContractNotice(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class CreditNote(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class DebitNote(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class DespatchAdvice(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class DocumentStatus(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class DocumentStatusRequest(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class ExceptionCriteria(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class ExceptionNotification(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class Forecast(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class ForecastRevision(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class ForwardingInstructions(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class FreightInvoice(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class FulfilmentCancellation(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class GoodsItemItinerary(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class GuaranteeCertificate(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class InstructionForReturns(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class InventoryReport(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class Invoice(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class ItemInformationRequest(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class Order(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class OrderCancellation(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class OrderChange(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class OrderResponse(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class OrderResponseSimple(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class PackingList(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class PriorInformationNotice(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class ProductActivity(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class Quotation(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class ReceiptAdvice(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class Reminder(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class RemittanceAdvice(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class RequestForQuotation(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class RetailEvent(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class SelfBilledCreditNote(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class SelfBilledInvoice(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class Statement(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class StockAvailabilityReport(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class Tender(DocumentDescriptor):
    """
    Description: A document whereby an economic operator (the tenderer)
    makes a formal offer (the tender) to a contracting authority to execute
    an order for the supply or purchase of goods, or for the execution of
    work, according to the terms of a proposed contract.
    """
    def __init__(self):
        self._fields = ()


class TendererQualification(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class TendererQualificationResponse(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class TenderReceipt(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class TradeItemLocationProfile(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class TransportationStatus(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class TransportationStatusRequest(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class TransportExecutionPlan(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class TransportExecutionPlanRequest(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class TransportProgressStatus(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class TransportProgressStatusRequest(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class TransportServiceDescription(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class TransportServiceDescriptionRequest(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class UtilityStatement(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class Waybill(DocumentDescriptor):
    def __init__(self):
        self._fields = ()


class BusinessDocumentTemplate(metaclass=Singleton):
    """
    Generate the various business components dynamically.
    This class serves as a factory for generating business components.
    Each component type is generated from a registry of defined UBL base
    components e.g BIE
    """
    _template = None
    _schemas = None

    # Declare the descriptor of this class to prevent illegal external access

    class Templates:
        def __init__(self):
            self.application_response = ApplicationResponse()
            self.attached = AttachedDocument()
            self.unawarded_notification = UnawardedNotification()
            self.bill_of_lading = BillOfLading()
            self.call_for_tenders = CallForTenders()
            self.catalogue = Catalogue()
            self.catalogue_deletion = CatalogueDeletion()
            self.catalogue_item_specification_update = \
                CatalogueItemSpecificationUpdate()
            self.catalogue_pricing_update = CataloguePricingUpdate()
            self.catalogue_request = CatalogueRequest()
            self.certificate_of_origin = CertificateOfOrigin()
            self.contract_award_notice = ContractAwardNotice()
            self.contract_notice = ContractNotice()
            self.credit_note = CreditNote()
            self.debit_note = DebitNote()
            self.despatch_advice = DespatchAdvice()
            self.document_status = DocumentStatus()
            self.document_status_request = DocumentStatusRequest()
            self.exception_criteria = ExceptionCriteria()
            self.exception_notification = ExceptionNotification()
            self.forecast = Forecast()
            self.forecast_revision = ForecastRevision()
            self.forwarding_instructions = ForwardingInstructions()
            self.freight_invoice = FreightInvoice()
            self.fulfilment_cancellation = FulfilmentCancellation()
            self.goods_item_itinerary = GoodsItemItinerary()
            self.guarantee_certificate = GuaranteeCertificate()
            self.instruction_for_returns = InstructionForReturns()
            self.inventory_report = InventoryReport()
            self.invoice = Invoice()
            self.item_information_request = ItemInformationRequest()
            self.order = Order()
            self.order_cancellation = OrderCancellation()
            self.order_change = OrderChange()
            self.order_response = OrderResponse()
            self.order_response_simple = OrderResponseSimple()
            self.packing_list = PackingList()
            self.prior_information_notice = PriorInformationNotice()
            self.product_activity = ProductActivity()
            self.quotation = Quotation()
            self.receipt_advice = ReceiptAdvice()
            self.reminder = Reminder()
            self.remittance_advice = RemittanceAdvice()
            self.request_for_quotation = RequestForQuotation()
            self.retail_event = RetailEvent()
            self.self_billed_credit_note = SelfBilledCreditNote()
            self.self_billed_invoice = SelfBilledInvoice()
            self.statement = Statement()
            self.stock_availability_report = StockAvailabilityReport()
            self.tender = Tender()
            self.tenderer_qualification = TendererQualification()
            self.tenderer_qualification_response = \
                TendererQualificationResponse()
            self.tender_receipt = TenderReceipt()
            self.trade_item_location_profile = TradeItemLocationProfile()
            self.transportation_status = TransportationStatus()
            self.transportation_status_request = TransportationStatusRequest()
            self.transport_execution_plan = TransportExecutionPlan()
            self.transport_execution_plan_request = \
                TransportExecutionPlanRequest()
            self.transport_progress_status = TransportProgressStatus()
            self.transport_progress_status_request = \
                TransportProgressStatusRequest()
            self.transport_service_description = TransportServiceDescription()
            self.transport_service_description_request = \
                TransportServiceDescriptionRequest()
            self.utility_statement = UtilityStatement()
            self.waybill = Waybill()

    class Schemas:
        # URI schema definition for listed documents
        def __init__(self):
            base_url = 'http://docs.oasis-open.org/ubl/os-UBL-2.1/UBL-2.1.html'
            self.application_response = \
                '%s%s' % (base_url, '#T-APPLICATION-RESPONSE')
            self.attached = \
                '%s%s' % (base_url, '#T-ATTACHED-DOCUMENT')
            self.awarded_notification = \
                '%s%s' % (base_url, '#T-AWARDED-NOTIFICATION')
            self.bill_of_lading = \
                '%s%s' % (base_url, '#T-BILL-OF-LADING')
            self.call_for_tenders = \
                '%s%s' % (base_url, '#T-CALL-FOR-TENDERS')
            self.catalogue = \
                '%s%s' % (base_url, '#T-CATALOGUE')
            self.catalogue_deletion = \
                '%s%s' % (base_url, '#T-CATALOGUE-DELETION')
            self.catalogue_item_specification_update = \
                '%s%s' % (base_url, '#T-CATALOGUE-ITEM-SPECIFICATION-UPDATE')
            self.catalogue_pricing_update = \
                '%s%s' % (base_url, '#T-CATALOGUE-PRICING-UPDATE')
            self.catalogue_request = \
                '%s%s' % (base_url, '#T-CATALOGUE-REQUEST')
            self.certificate_of_origin = \
                '%s%s' % (base_url, '#T-CERTIFICATE-OF-ORIGIN')
            self.contract_award_notice = \
                '%s%s' % (base_url, '#T-CONTRACT-AWARD-NOTICE')
            self.contract_notice = \
                '%s%s' % (base_url, '#T-CONTRACT-NOTICE')
            self.credit_note = \
                '%s%s' % (base_url, '#T-CREDIT-NOTE')
            self.debit_note = \
                '%s%s' % (base_url, '#T-DEBIT-NOTE')
            self.despatch_advice = \
                '%s%s' % (base_url, '#T-DESPATCH-ADVICE')
            self.document_status = \
                '%s%s' % (base_url, '#T-DOCUMENT-STATUS')
            self.document_status_request = \
                '%s%s' % (base_url, '#T-DOCUMENT-STATUS-REQUEST')
            self.exception_criteria = \
                '%s%s' % (base_url, '#T-EXCEPTION-CRITERIA')
            self.exception_notification = \
                '%s%s' % (base_url, '#T-EXCEPTION-NOTIFICATION')
            self.forecast = \
                '%s%s' % (base_url, '#T-FORECAST')
            self.forecast_revision = \
                '%s%s' % (base_url, '#T-FORECAST-REVISION')
            self.forwarding_instructions = \
                '%s%s' % (base_url, '#T-FORWARDING-INSTRUCTIONS')
            self.freight_invoice = \
                '%s%s' % (base_url, '#T-FREIGHT-INVOICE')
            self.fulfilment_cancellation = \
                '%s%s' % (base_url, '#T-FULFILMENT-CANCELLATION')
            self.goods_item_itinerary = \
                '%s%s' % (base_url, '#T-GOODS-ITEM-ITINERARY')
            self.guarantee_certificate = \
                '%s%s' % (base_url, '#T-GUARANTEE-CERTIFICATE')
            self.instruction_for_returns = \
                '%s%s' % (base_url, '#T-INSTRUCTION-FOR-RETURNS')
            self.inventory_report = \
                '%s%s' % (base_url, '#T-INVENTORY-REPORT')
            self.invoice = \
                '%s%s' % (base_url, '#T-INVOICE')
            self.item_information_request = \
                '%s%s' % (base_url, '#T-ITEM-INFORMATION-REQUEST')
            self.order = \
                '%s%s' % (base_url, '#T-ORDER')
            self.order_cancellation = \
                '%s%s' % (base_url, '#T-ORDER-CANCELLATION')
            self.order_change = \
                '%s%s' % (base_url, '#T-ORDER-CHANGE')
            self.order_response = \
                '%s%s' % (base_url, '#T-ORDER-RESPONSE')
            self.order_response_simple = \
                '%s%s' % (base_url, '#T-ORDER-RESPONSE-SIMPLE')
            self.packing_list = \
                '%s%s' % (base_url, '#T-PACKING-LIST')
            self.prior_information_notice = \
                '%s%s' % (base_url, '#T-PRIOR-INFORMATION-NOTICE')
            self.product_activity = \
                '%s%s' % (base_url, '#T-PRODUCT-ACTIVITY')
            self.quotation = \
                '%s%s' % (base_url, '#T-QUOTATION')
            self.receipt_advice = \
                '%s%s' % (base_url, '#T-RECEIPT-ADVICE')
            self.reminder = \
                '%s%s' % (base_url, '#T-REMINDER')
            self.remittance_advice = \
                '%s%s' % (base_url, '#T-REMITTANCE-ADVICE')
            self.request_for_quotation = \
                '%s%s' % (base_url, '#T-REQUEST-FOR-QUOTATION')
            self.retail_event = \
                '%s%s' % (base_url, '#T-RETAIL-EVENT')
            self.self_billed_credit_note = \
                '%s%s' % (base_url, '#T-SELF-BILLED-CREDIT-NOTE')
            self.self_billed_invoice = \
                '%s%s' % (base_url, '#T-SELF-BILLED-INVOICE')
            self.statement = \
                '%s%s' % (base_url, '#T-STATEMENT')
            self.stock_availability_report = \
                '%s%s' % (base_url, '#T-STOCK-AVAILABILITY-REPORT')
            self.tender = \
                '%s%s' % (base_url, '#T-TENDER')
            self.tender_receipt = \
                '%s%s' % (base_url, '#T-TENDER-RECEIPT')
            self.tenderer_qualification_response = \
                '%s%s' % (base_url, '#T-TENDERER-QUALIFICATION-RESPONSE')
            self.tenderer_qualification = \
                '%s%s' % (base_url, '#T-TENDERER-QUALIFICATION')
            self.trade_item_location_profile = \
                '%s%s' % (base_url, '#T-TRADE-ITEM-LOCATION-PROFILE')
            self.transport_execution_plan = \
                '%s%s' % (base_url, '#T-TRANSPORT-EXECUTION-PLAN')
            self.transport_execution_plan_request = \
                '%s%s' % (base_url, '#T-TRANSPORT-EXECUTION-PLAN-REQUEST')
            self.transport_progress_status = \
                '%s%s' % (base_url, '#T-TRANSPORT-PROGRESS-STATUS')
            self.transport_progress_status_request = \
                '%s%s' % (base_url, '#T-TRANSPORT-PROGRESS-STATUS-REQUEST')
            self.transport_service_description = \
                '%s%s' % (base_url, '#T-TRANSPORT-SERVICE-DESCRIPTION')
            self.transport_service_description_request = \
                '%s%s' % (base_url, '#T-TRANSPORT-SERVICE-DESCRIPTION-REQUEST')
            self.transportation_status = \
                '%s%s' % (base_url, '#T-TRANSPORTATION-STATUS')
            self.transportation_status_request = \
                '%s%s' % (base_url, '#T-TRANSPORTATION-STATUS-REQUEST')
            self.unawarded_notification = \
                '%s%s' % (base_url, '#T-UNAWARDED-NOTIFICATION')
            self.utility_statement = \
                '%s%s' % (base_url, '#T-UTILITY-STATEMENT')
            self.waybill = \
                '%s%s' % (base_url, '#T-WAYBILL')

    def __init__(self):
        # load the business document template from db or
        # file using singleton pattern
        if not self._template:
            self._template = self.Templates()
        if not self._schemas:
            self._schemas = self.Schemas()
        super().__init__()

    def document_fields(self, document):
        return getattr(self._template, document, None)

    def document_definition(self, document):
        fields = ((x, None) for x in getattr(self._template, document,
                                             None) if x is not None)
        return OrderedDict.fromkeys(fields)

    def schema(self, document):
        return getattr(self._schemas, document, None)

    @property
    def document_schemas(self):
        return vars(self._schemas)

    @property
    def document_registry(self):
        return vars(self._template).keys()


class DocumentAttributeMixin:

    # @todo: deprecated class as behaviour defined dynamically

    def __getitem__(self, item):
        if item not in self.__slots__ or item not in self.__dict__:
            raise IndexError('Index does not exist in Business Document')
        return getattr(self, item, None)

    def __setitem__(self, key, value):
        if key not in self.__slots__ or key not in self.__dict__:
            raise IndexError('Index does not exist in Business Document')
        setattr(self, key, value)

    def __delattr__(self, item):
        raise AttributeError('Attribute cannot be deleted in Business Document')

    def __getattribute__(self, name):
        if name in self._definition:
            return getattr(self, name, None)
        return object.__getattribute__(self, name)


def _dynamic_document(document_type, fields, module=None):

    _class_definition = """\
class {document_type}:
    __slots__ = {fields}.keys()

    def __init__(self):
        for field, value in {fields}.items():
            setattr(self, field, value)

    def __getitem__(self, item):
        if item not in self.__slots__ or item not in self.__dict__:
            raise IndexError('Index does not exist in Business Document')
        return getattr(self, item, None)

    def __setitem__(self, key, value):
        if key not in self.__slots__ or key not in self.__dict__:
            raise IndexError('Index does not exist in Business Document')
        setattr(self, key, value)

    def __delattr__(self, item):
        raise AttributeError('Attribute cannot be deleted in Business Document')

    def __getattribute__(self, name):
        if name in self._definition:
            return getattr(self, name, None)
        return object.__getattribute__(self, name)

    """
    _class_definition.format(document_type=document_type, fields=fields)
    _tmp_namespace = 'ubl_%s' % document_type.lower()
    namespace = dict(__name__=_tmp_namespace)
    exec(_class_definition, namespace)
    class_impl = namespace[_tmp_namespace]
    class_impl._source = _class_definition
    if module is None:
        module = 'ubl'
    class_impl.__module__ = str(module)
    return class_impl()


class BusinessDocumentPrototype:
    """
    The document prototype used to produce the various types of documents
    defined in the UBL 2.1 implementation.
    This class has a factory method which generate the named document and
    returns a copy of it. To improve efficiency, an instance of each copy of
    document is bound to the class enabling caching of created document.
    Upon creating a new type of document, the instance is replaced. This is
    resource saving where a given type of document is created in a loop
    """
    __slots__ = ('instance', '_fields', '_definition', '_schema')

    def __init__(self):
        self.instance = None
        self._fields = None
        self._definition = None
        self._schema = None

    def __init_subclass__(self, *args, **kwargs):
        raise Exception('Document Factory not to be extended')

    @staticmethod
    def produce_document(self, document):
        # if the document is not in document lists, exit
        # if the document is in list, then check if it's instance
        # else create instance and return a copy
        if not isinstance(document, str):
            document = str(document)
        if document not in BusinessDocumentTemplate.document_registry:
            raise TypeError('Unrecognised document type specified')
        else:
            bt = BusinessDocumentTemplate()
            if not self.instance:
                self._name = document
                self._definition = bt.document_definition(document)
                self._fields = bt.document_fields(document)
                self._schema = bt.schema(document)
                self.instance = _dynamic_document(self._name, self._fields)
            elif document != self.instance.__name__:
                self.instance = _dynamic_document(self._name, self._fields)

        return copy.deepcopy(self.instance)


class DocumentRevisions:
    """
    Keeps instances of Business documents generated during the life cycle of
    an operation or business service.
    Each record is a signed timestamp and retrievable from internal list
    """
    def __init__(self):
        self._revisions = OrderedDict()

    def revisions(self):
        return self._revisions.items()

    def __setitem__(self, key, value):
        stamped_key = sha512(datetime.utcnow() + key).hexdigest()
        self._revisions[stamped_key] = value
